= Testify Docs Site and Playbook Project

This is the playbook project for the Testify docs site using Anotrra.
You can view the site produced by the Antora playbook ([.path]_antora-playbook.yml_) stored in this project at https://testibus-team4.github.io/yoko .

== Antora Playbook

An Antora playbook is responsible for generating a documentation site.
It contains the instructions a user wants to relay to the Antora site generator.
These instructions include the content Antora should collect and the UI it should apply to the generated site.

The file [.path]_antora-playbook.yml_ in this repository is the playbook used to produce the demo site.
It tells Antora where to find the Componets with the content for the site and where to find the default UI.

== Generate Site
You can make changes to the repo and view the local changes by generating a local site. After cloning this playbook project repository to your computer you can generate the demo site by using the command `antora --fetch antora-playbook.yml` within the same directory as the antora playbook. To be able to run the command you need to install antora first. Installation instructions can be found at https://docs.antora.org/antora/latest/install/install-antora/ .