= Testify Docs Site and Playbook Project

This is the playbook project for the Testify docs site using Anotrra.
You can view the site produced by the Antora playbook ([.path]_antora-playbook.yml_) stored in this project at https://testibus-team4.github.io/yoko

== Antora Playbook

An {url-docs-playbook}[Antora playbook] is responsible for generating a documentation site.
It contains the instructions a user wants to relay to the Antora site generator.
These instructions include the content Antora should collect and the UI it should apply to the generated site.

The file [.path]_antora-playbook.yml_ in this repository is the playbook used to produce the demo site.
It tells Antora where to find the Component A and Component B remote content repositories and default UI.

== Generate the Demo Site

After cloning this playbook project repository to your computer or setting up your own playbook for the demo site (see the {url-docs-quickstart}[Antora quickstart] for instructions) you can generate the demo site by {url-docs-run}[running Antora].

== Copyright and License

Copyright (C) 2017-present by OpenDevise Inc. and the individual contributors to Antora.

Use of this software is granted under the terms of the https://www.mozilla.org/en-US/MPL/2.0/[Mozilla Public License Version 2.0] (MPL-2.0).
See link:LICENSE[] to find the full license text.

== Authors

Development of Antora is led and sponsored by {url-opendevise}[OpenDevise Inc].

